name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: Fellyipe
          template: classic
          base: ""
          config_common: '{"css": ".footer { display: none; }"}'
          
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_skipped: Roca-express_App
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
